spring:
  application:
    name: ai-service
  config:
    import: nacos:ai-service-dev.yaml
  cloud:
    nacos:
      discovery:
        server-addr: localhost:8848
      config:
        server-addr: localhost:8848
        file-extension: yaml

langchain4j:
  community:
    dashscope:
      chat-model:
        api-key: sk-ce9c611e301c4055b203fdec4aa10544
        #model-name: deepseek-v3
        #model_name: qwen-max
        model-name: qwen-max-latest